const vokabeln = [
   ["Hallo!","¡Hola!"],
["Guten Morgen!; Guten Tag!","¡Buenos días!"],
["Wie geht´s?","¿Qué tal?"],
["gut","bien"],
["Danke.","Gracias."],
["und","y"],
["Und du?","¿Y tú?"],
["auch","también"],
["Ich bin …","Yo soy…"],
["Ich heiße …","Me llamo…"],
["Wie heißt du?","¿Cómo te llamas?"],
["Wie …?","¿Cómo…?"],
["ja","sí"],
["von; aus","de"],
["Woher …?","¿De dónde… ?"],
["Woher kommst du?","¿De dónde eres?"],
["Deutschland","Alemania"],
["Auf Wiedersehen!; Tschüs!","¡Adiós!"],
["Bis später!","¡Hasta luego!"],
["sehr","muy"],
["So so.; Es geht.","Así así."],
["schlecht","mal"],
["Guten Tag!; Guten Abend!","¡Buenas tardes!"],
["Guten Abend!; Gute Nacht!","¡Buenas noches!"],
["Wie ist dein Nachname?","¿Cómo es tu apellido?"],
["er/sie/es ist","es"],
["der Nachname","el apellido"],
["Man schreibt …","Se escribe…"],
["Wie schreibt man …?","¿Cómo se escribe… ?"],
["mit Akzent","con acento"],
["mit Umlaut","con dos puntos"],
["Doppel-","doble"],
["der Park","el parque"],
["das Hotel","el hotel"],
["das (Stadt) Zentrum","el centro"],
["der Zoo","el zoo"],
["das Restaurant","el restaurante"],
["das Museum","el museo"],
["der Platz","la plaza"],
["die Buchhandlung","la librería"],
["das Haus; die Wohnung","la casa"],
["die Nummer; die Zahl","el número"],
["der Fuchs","el zorro"],
["der Hund","el perro"],
["die Katze","el gato"],
["der Elefant","el elefante"],
["der Bär","el oso"],
["das Pferd","el caballo"],
["der Esel","el burro"],
["die Biene","la abeja"],
["die Vogelspinne; die Tarantel","la tarántula"],
["der Affe","el mono"],
["der Frosch","la rana"],
["die Kuh","la vaca"],
["Ich bin ... Jahre alt.","Tengo... años."],
["mein; meine","mi"],
["das Handy","el móvil"],
["das Telefon","el teléfono"],
["aber","pero"],
["die Stadt","la ciudad"],
["jetzt","ahora"],
["Wie alt bist du?","¿Cuántos años tienes?"],
["die Welt","el mundo"],
["die Schule","el colegio"],
["die Mutter","la madre"],
["der Vater","el padre"],
["die Eltern","los padres (pl.)"],
["der Bruder / die Schwester","el hermano / la hermana"],
["die Geschwister","los hermanos"],
["der Freund / die Freundin","el amigo / la amiga"],
["das Haustier","la mascota"],
["Er / Sie heißt …","Se llama…"],
["dein / deine","tu"],
["besser","mejor"],
["nein; nicht; kein, -e","no"],
["haben","tener (irr.)"],
["Wer …?","¿Quién…? / ¿Quiénes…?"],
["der Lehrer / die Lehrerin","el profesor / la profesora"],
["arbeiten","trabajar"],
["in; auf; an","en"],
["sprechen; reden","hablar"],
["Deutsch, die deutsche Sprache","el alemán"],
["(Ja) , natürlich!","¡Claro!"],
["Spanisch, die spanische Sprache","el español"],
["außerdem","además"],
["lernen","estudiar"],
["Englisch, die englische Sprache","el inglés"],
["zu Hause","en casa"],
["mit","con"],
["immer","siempre"],
["Welche, -r, -s …?; Was für ein, -e ...?; Was ...?","¿Qué… ?"],
["die Sprache","el idioma"],
["etw./jdn hören","escuchar algo/a alguien"],
["antworten","contestar"],
["fragen","preguntar"],
["Schau (mal).","Mira."],
["etw./jdn (an) schauen","mirar algo/a alguien"],
["Das ist…","Este es… / Esta es…"],
["der Junge / das Mädchen","el chico / la chica"],
["(Kommt) Herein!","¡Adelante!"],
["Was ist los?","¿Qué pasa?"],
["das Problem","el problema"],
["etw./jdn suchen","buscar algo/a alguien"],
["das Geheimnis","el secreto"],
["die Idee","la idea"],
["Er / Sie hat keine Ahnung davon.","No tiene ni idea de esto."],
["die Überraschung","la sorpresa"],
["wie","como"],
["der Rucksack","la mochila"],
["nichts","nada"],
["Was …?","¿Qué...?"],
["die Kiste; die Schachtel","la caja"],
["das Monster","el monstruo"],
["der Laden; das Geschäft","la tienda"],
["das Tier","el animal"],
["die Zoohandlung","la tienda de animales"],
["der Papa / die Mama","el papá / la mamá"],
["Keine Widerrede!","¡Nada de peros!"],
["nach; (hin) zu","a"],
["sofort","ahora mismo"],
["sein","ser (irr.)"],
["der Hamster","el hámster"],
["der Fisch","el pez"],
["das Meerschweinchen","el conejillo de Indias"],
["die Schildkröte","la tortuga"],
["der Wellensittich","el periquito"],
["das (Stadt) Viertel","el barrio"],
["die Eisdiele","la heladería"],
["der Supermarkt","el supermercado"],
["das Café; die Cafeteria","la cafetería"],
["die Bibliothek","la biblioteca"],
["das Kino","el cine"],
["das Sportzentrum","el polideportivo"],
["das Bekleidungsgeschäft","la tienda de ropav"],
["der Baum","el árbol"],
["die Apotheke","la farmacia"],
["das Einkaufszentrum","el centro comercial"],
["es gibt; da ist/sind","hay"],
["viel","mucho, -a"],
["wenig","poco, -a"],
["richtig","correcto, -a"],
["groß","grande"],
["modern","moderno, -a"],
["klein","pequeño, -a"],
["schön","bonito, -a"],
["interessant","interesante"],
["Lieblings-","favorito, -a"],
["alt","antiguo, -a"],
["hässlich","feo, -a"],
["langweilig","aburrido, -a"],
["sich befinden; sein","estar (irr.)"],
["die Nachricht","el mensaje"],
["seltsam","raro, -a"],
["Vorsicht!","¡Cuidado!"],
["der Hinweis","la pista"],
["hier","aquí"],
["das Buch","el libro"],
["Los!","¡Vamos!"],
["die Straße","la calle"],
["auf etw./jdn warten","esperar algo/a alguien"],
["die Antwort","la respuesta"],
["etw. schicken","mandar algo"],
["schon","ya"],
["Wo …?","¿Dónde… ?"],
["gegenüber von","enfrente de"],
["die Eintrittskarte","la entrada"],
["für","para"],
["der Film","la película"],
["neben","al lado de"],
["vor","delante de"],
["hinter","detrás de"],
["zwischen","entre"],
["in der Nähe von","cerca de"],
["weit entfernt von","lejos de"],
["das Foto","la foto"],
["der Ort; der Platz","el lugar"],
["weil","porque"],
["der Saft","el zumo"],
["das Obst","la fruta"],
["der Fruchtsaft","el zumo de frutas"],
["lecker","rico, -a"],
["wohnen; leben","vivir"],
["das Wochenende; am Wochenende","el fin de semana"],
["(immer) am Wochenende","los fines de semana"],
["etw. trinken; etw. nehmen","tomar algo"],
["etw. essen","comer algo"],
["das belegte Brötchen","el bocadillo"],
["etw. trinken","beber algo"],
["etwas","algo"],
["vor","antes de"],
["gut","bueno, -a"],
["jdn anrufen","llamar a alguien"],
["das Zimmer","la habitación"],
["die Katastrophe","el desastre"],
["der Moment","el momento"],
["etw. (an) schauen; etw. sehen","ver (irr.) algo"],
["Warum ...?","¿Por qué...?"],
["die Zeit","el tiempo"],
["das Spiel","el juego"],
["der Boden","el suelo"],
["das Glück","la suerte"],
["der Schulhof","el patio"],
["der Computerraum","la sala de Informática"],
["das Sekretariat","la secretaría"],
["die Turnhalle","el gimnasio"],
["der Klassenraum","el aula"],
["der Taschenrechner","la calculadora"],
["der Bleistift","el lápiz"],
["der Ordner","la carpeta"],
["der Radiergummi","la goma"],
["das Heft","el cuaderno"],
["das Federmäppchen","el estuche"],
["der Kugelschreiber","el bolígrafo"],
["der Füller","la pluma"],
["Wie viel ...?","¿Cuánto, -a… ?"],
["heute","hoy"],
["September","septiembre"],
["erste, -r, -s","primero, -a"],
["der Tag","el día"],
["der Unterricht","la clase"],
["etw. glauben; etw. meinen","creer algo"],
["(an) kommen","llegar"],
["die Minute","el minuto"],
["spät; zu spät","tarde"],
["Entschuldigung.","Perdón."],
["neu","nuevo, -a"],
["Mathematik","las Matemáticas"],
["der Klassenlehrer / die Klassenlehrerin","el tutor / la tutora"],
["der Tisch","la mesa"],
["etw. lesen","leer algo"],
["die Liste","la lista"],
["noch einmal; schon wieder","otra vez"],
["etw. brauchen","necesitar algo"],
["die Frage","la pregunta"],
["Hör mal!","¡Oye!"],
["der Herr / die Frau","el señor / la señora"],
["etw./jdm schreiben","escribir algo/a alguien"],
["verärgert","enfadado, -a"],
["sich kaputtlachen","explotar de la risa"],
["die Karotte","la zanahoria"],
["Wie spät ist es?","¿Qué hora es?"],
["morgens","de la mañana"],
["nachmittags; abends","de la tarde"],
["abends; nachts","de la noche"],
["das Unterrichtsfach","la asignatura"],
["Spanisch (als Schulfach, wie das Fach Deutsch in Deutschland)","la Lengua Castellana y Literatura"],
["Geschichte und Erdkunde (Schulfach)","las Ciencias Sociales"],
["Sport (Schulfach)","la Educación Física"],
["Französisch (Schulfach)","el Francés"],
["Naturkunde (Schulfach)","las Ciencias Naturales"],
["Kunst (Schulfach)","la Expresión Plástica"],
["Musik (Schulfach)","la Música"],
["Dir gefällt etw.; Du magst etw. (tun).","Te gusta algo / hacer algo."],
["Mir gefällt etw.; Ich mag etw. (tun)","Me gusta algo / hacer algo."],
["der Stundenplan","el horario"],
["der Montag","el lunes"],
["der Dienstag","el martes"],
["der Mittwoch","el miércoles"],
["der Donnerstag","el jueves"],
["der Freitag","el viernes"],
["der Samstag","el sábado"],
["der Sonntag","el domingo"],
["die Pause","el recreo"],
["von … bis","de… a"],
["um …","a las…"],
["chatten","chatear"],
["über","sobre"],
["Wie war …?","¿Qué tal… ?"],
["euer, eure","vuestro, -a"],
["dieses Jahr","este año"],
["unser, unsere","nuestro, -a"],
["streng","estricto, -a"],
["die Hausaufgaben","los deberes (pl.)"],
["die Klasse","la clase"],
["das Gebäude; das Wohnhaus","el edificio"],
["sich verabreden; sich treffen","quedar"],
["lustig","divertido, -a"],
["die Geschichte","la historia"],
["bis","hasta"],
["morgen","mañana"],
["Wie langweilig!","¡Qué rollo!"],
["auch nicht","tampoco"],
["die Klassenarbeit","el examen"],
["nur","solo"],
["zeichnen","dibujar"],
["die Musik","la música"],
["sehr; viel","mucho"],
["erlauben","permitir"],
["Ihm / Ihr gefällt etw.; Er/Sie mag etwas (tun).","Le gusta algo / hacer algo."],
["das Bett","la cama"],
["der Schreibtisch","el escritorio"],
["der Schrank","el armario"],
["das Regal","la estantería"],
["der Stuhl","la silla"],
["die Gitarre","la guitarra"],
["der Fernseher","el televisor"],
["der Computer","el ordenador"],
["das Poster","el póster"],
["das Fenster","la ventana"],
["die Lampe","la lámpara"],
["die Tür","la puerta"],
["die Wand","la pared"],
["die CD","el CD"],
["auf","encima de"],
["unter","debajo de"],
["links von","a la izquierda de"],
["rechts von","a la derecha de"],
["der Deutsche / die Deutsche","el alemán / la alemana"],
["etw. aufräumen","ordenar algo"],
["Das stimmt doch, oder?; … nicht wahr?","¿Verdad?"],
["etw. tun können; etw. tun dürfen","poder (-ue-) hacer algo"],
["etw. anfassen","tocar algo"],
["die Sache; das Ding","la cosa"],
["sehr geehrte, -r","estimado, -a"],
["der Brief","la carta"],
["etw. machen","hacer (irr.) algo"],
["etw. tun müssen","tener que hacer algo"],
["der Schüler / die Schülerin","el alumno / la alumna"],
["der Gruß","el saludo"],
["Das darf doch wohl nicht wahr sein.","Esto no puede ser."],
["Wie entsetzlich!","¡Qué horror!"],
["auf etw. Lust haben; Lust haben etw. zu tun","tener ganas de algo / de hacer algo"],
["dann","entonces"],
["so; auf diese Weise","así"],
["die E-Mail","el correo (electrónico)"],
["etw. wollen","querer (-ie-) algo"],
["in Ruhe lassen","dejar tranquilo, -a"],
["ruhig","tranquilo, -a"],
["letzte, -r, -s","último, -a"],
["zum letzten Mal","por última vez"],
["etw. (hinein) legen; etw. setzen; etw. stellen","poner (-g-) algo"],
["Es tut mir leid.","Lo siento."],
["die Fernsehserie","la serie"],
["das Fernsehen","la tele(visión)"],
["dann; danach","después"],
["Jetzt reicht’s )mir( aber!","¡Basta ya!"],
["Hausarrest haben","estar castigado, -a sin salir"],
["die Freizeit","el tiempo libre"],
["gehen; fahren","ir (irr.)"],
["shoppen gehen","ir de compras"],
["spielen (Musikinstrument","tocar"],
["Rad fahren","montar en bicicleta"],
["das Fahrrad","la bicicleta"],
["mit jdm etw. spielen","jugar (-ue-) a algo con alguien"],
["der Fußball","el fútbol"],
["telefonieren","hablar por teléfono"],
["der Sport","el deporte"],
["Mir ja.; Ich ja.","A mí sí."],
["Mir nicht.; Ich nicht.","A mí no."],
["Mir auch.","A mí también."],
["Mir auch nicht.; Ich auch nicht.","A mí tampoco."],
["(am) Morgen; (am) Vormittag","por la mañana"],
["ausgehen","salir (-g-)"],
["(am) Nachmittag","por la tarde"],
["das Training","el entrenamiento"],
["das Fußballspiel","el partido de fútbol"],
["die Party; das Fest","la fiesta"],
["Wie …!","¡Qué… !"],
["toll; klasse","guay"],
["genial","genial"],
["etw. kaufen","comprar algo"],
["die Pizza","la pizza"],
["zuerst","primero"],
["sicher; sicherlich","seguramente"],
["die Hilfe","la ayuda"],
["schnell","rápidamente"],
["dumm","tonto, -a"],
["Einverstanden.; O.K.","Vale."],
["perfekt","perfecto, -a"],
["Wann …?","¿Cuándo…?"],
["der Geburtstag","el cumpleaños"],
["Januar","enero"],
["Februar","febrero"],
["März","marzo"],
["April","abril"],
["Mai","mayo"],
["Juni","junio"],
["Juli","julio"],
["August","agosto"],
["September","septiembre"],
["Oktober","octubre"],
["November","noviembre"],
["Dezember","diciembre"],
["das Geschenk","el regalo"],
["anfangen; beginnen","empezar (-ie-)"],
["der Frühling","la primavera"],
["die Ferien; der Urlaub","las vacaciones"],
["der Sommer","el verano"],
["der Strand","la playa"],
["Weihnachten","la Navidad"],
["der Winter","el invierno"],
["der Herbst","el otoño"],
["etw. feiern","celebrar algo"],
["dort","allí"],
["wichtig","importante"],
["Bitte.","Por favor."],
["um … zu","para (+ inf.)"],
["etw. organisieren","organizar algo"],
["der Kuss","el beso"],
["jdn einladen","invitar a alguien"],
["die Aufgabe","la tarea"],
["einfach; leicht","fácil"],
["etw./jdn besuchen","visitar algo/a alguien"],
["der Streber, die Streberin","el empollón, la empollona"],
["der Großvater, die Großmutter","el abuelo, la abuela"],
["die Großeltern","los abuelos (pl.)"],
["allein, -e","solo, -a"],
["vielleicht","a lo mejor"],
["kommen","venir (irr.)"],
["die Information","la información"],
["jdn überraschen","sorprender a alguien"],
["die Themenparty","la fiesta temática"],
["oder","o"],
["notwendig","necesario, -a"],
["die Einladung","la invitación"],
["das Essen","la comida"],
["das Getränk","la bebida"],
["die Torte; der Kuchen","la tarta"],
["etw. dekorieren; etw. schmücken","decorar algo"],
["etw. zubereiten; etw. vorbereiten","preparar algo"],
["der Kartoffelchip","la patata frita"],
["das Wasser","el agua (f.)"],
["etw./jdn (mit) bringen","traer (irr.) algo/a alguien"],
["das Lied","la canción"],
["der Plan","el plan"],
["typisch","típico, -a"],
["die Schokolade","el chocolate"],
["jeder / jede","cada persona"],
["jdn veräppeln","tomar el pelo a alguien"],
["die Packung","el paquete"],
["der Keks","la galleta"],
["der Käse","el queso"],
["die Tüte","la bolsa"],
["die Flasche","la botella"],
["das Erfrischungsgetränk","el refresco"],
["die Orange","la naranja"],
["das Baguette","la barra de pan"],
["das Brot","el pan"],
["kosten","costar (-ue-)"],
["der Euro","el euro"],
["der Cent","el céntimo"],
["der Rock","la falda"],
["die Bluse","la blusa"],
["das T-Shirt","la camiseta"],
["die Jacke","la chaqueta"],
["die Socke","el calcetín"],
["der Schuh","el zapato"],
["die Sportschuhe","las zapatillas de deporte (pl.)"],
["die Jeans(hose)","los vaqueros (pl.)"],
["der Mantel","el abrigo"],
["die Hose","los pantalones"],
["der Schal","la bufanda"],
["der Handschuh","el guante"],
["der Pullover","el jersey"],
["die Brille","las gafas (pl.)"],
["die Sonnenbrille","las gafas de sol (pl.)"],
["der Badeanzug; die Badehose","el bañador"],
["das Kleid","el vestido"],
["die Sandale","la sandalia"],
["der Koffer","la maleta"],
["Ich glaub, ich spinne!","¡No me lo puedo creer!"],
["verbringen","pasar"],
["die Küste","la costa"],
["fast","casi"],
["alle; jede, -r, -s","todos, -as"],
["saber (irr.) algo","etw. wissen"],
["gracioso, -a","witzig"],
["verde","grün"],
["pues","also"],
["dieser, diese, dieses (hier)","este, -a, -os, -as"],
["dieser, diese, dieses (da)","ese, -a, -os, -as"],
["etw. lieber mögen","preferir (-ie-) algo"],
["rosa","rosa"],
["der Bikini","el bikini"],
["rot","rojo, -a"],
["Wie findest du …?","¿Qué te parece)n(…?"],
["Ich finde …","Me parece)n( …"],
["da","ahí"],
["blau","azul"],
["dunkel","oscuro, -a"],
["dir steht / dir stehen","te queda(n)"],
["Sie beachten uns überhaupt nicht.","Pasan completamente de nosotras."],
["eitel","presumido, -a"],
["mir steht / mir stehen","me queda(n)"],
["die Größe","la talla"],
["breit; weit","ancho, -a"],
["kurz","corto, -a"],
["zu + Adj.","demasiado"],
["lang","largo, -a"],
["eng","estrecho, -a"],
["jener, jene, jenes","aquel, aquella, aquellos, aquellas"],
["hell","claro, -a"],
["omamäßig","de abuela"],
["das (Speise) Eis","el helado"],
["der/die/das","que"],
["nächstes Mal","la próxima vez"],
["etw. tragen","llevar algo"],
["gelb","amarillo, -a"],
["orange(farbe)","naranja"],
["schwarz","negro, -a"],
["weiß","blanco, -a"],
["grau","gris"],
["braun","marrón"],
["lila","lila"],
];

let currentVokabelIndex = 0;
const deutscheVokabelDiv = document.getElementById("deutscheVokabel");
const spanischeVokabelDiv = document.getElementById("spanischeVokabel");

function loadNextVokabel() {
    if (currentVokabelIndex < vokabeln.length - 1) {
        currentVokabelIndex++;
    } else {
        currentVokabelIndex = 0;
    }
    updateVokabelAnzeige();
}

function updateVokabelAnzeige() {
    const [deutscheVokabel, spanischeVokabel] = vokabeln[currentVokabelIndex];
    deutscheVokabelDiv.textContent = deutscheVokabel;
    spanischeVokabelDiv.textContent = spanischeVokabel;
    deutscheVokabelDiv.style.display = "block";
    spanischeVokabelDiv.style.display = "none";
}

// Buttons
document.getElementById("btn-question").addEventListener("click", function() {
    deutscheVokabelDiv.style.display = "block";
    spanischeVokabelDiv.style.display = "none";
});

document.getElementById("btn-answer").addEventListener("click", function() {
    deutscheVokabelDiv.style.display = "none";
    spanischeVokabelDiv.style.display = "block";
});

document.getElementById("btn-play").addEventListener("click", function() {
    responsiveVoice.speak(vokabeln[currentVokabelIndex][1], "Spanish Female");
});

document.getElementById("btn-next").addEventListener("click", function() {
    loadNextVokabel();
});

updateVokabelAnzeige();
