package com.bueffeltier.data.hibernate.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ssss generated by hbm2java
 */
@Entity
@Table(name = "tbl_exercise", catalog = "bueffeltier")
//@Table(name="frage_antwort")
public class FrageAntwort implements java.io.Serializable
{

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "tr_id", unique = true, nullable = false, length = 10)
	private int id;

	@Column(name = "tr_question", nullable = true, length = 255)
	private String frage;

	@Column(name = "tr_answer", nullable = true, length = 255)
	private String antwort;

//    private int authorId;
	/**
	 *
	 */
	public FrageAntwort()
	{

	}

	/**
	 *
	 * @param frage
	 * @param antwort
	 */
	public FrageAntwort(String frage, String antwort)
	{
		this.frage = frage;
		this.antwort = antwort;
	}

	/**
	 *
	 * @return
	 */
	public int getID()
	{
		return id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 *
	 * @param nummer
	 */
	public void setNummer(int nummer)
	{
		this.id = nummer;
	}

	/**
	 *
	 * @return
	 */
	public String getFrage()
	{
		return frage;
	}

	/**
	 *
	 * @param frage
	 */
	public void setFrage(String frage)
	{
		this.frage = frage;
	}

	/**
	 *
	 * @return
	 */
	public String getAntwort()
	{
		return antwort;
	}

	/**
	 *
	 * @param antwort
	 */
	public void setAntwort(String antwort)
	{
		this.antwort = antwort;
	}
}
